- README.md
**Closes:** #1 
Adding `README.md` with the following sections:
1. Banner
2. Getting Started
1. Project Installation
2. Running the Development Environment
3. Configuring Node and NVM
3. `draft` Contributing
4. `draft` License
> Add README with instructions to install

- .github/workflows/deploy.yml
- pnpm-lock.yaml
Our Github action was configured for pushes on `main` branch instead of `master`. This PR intends to fix this.
> fix: branch name on ci

- .changeset/cuddly-shirts-ring.md
- design-system/react/src/components/Focus/Focus.stories.tsx
- design-system/react/src/components/Focus/Focus.test.tsx
- design-system/react/src/components/Focus/Focus.tsx
- design-system/react/src/components/Focus/FocusArrowNavigator.tsx
- design-system/react/src/components/Focus/FocusScope.tsx
- design-system/react/src/components/Focus/index.tsx
- design-system/react/src/components/index.tsx
> feat: add Focus component

- .changeset/sweet-hats-cheat.md
- design-system/react/src/components/Focus/FocusArrowNavigator.tsx
- design-system/react/src/components/Focus/FocusScope.tsx
> fix: export missing FocusScopeProps on Focus component

- .changeset/popular-jobs-trade.md
- common/config/package.json
- common/test-utils/package.json
- design-system/react/.storybook/main.js
- design-system/react/package.json
- design-system/react/src/components/Input/Input.stories.tsx
- design-system/react/src/components/Input/Input.test.tsx
- design-system/react/src/components/Input/Input.tsx
- design-system/react/src/components/Input/InputAmount.tsx
- design-system/react/src/components/Input/InputNumber.tsx
- package.json
- pnpm-lock.yaml
✨ Close #8
Add new `<Input.Number>` component that uses `react-number-format` under the hood to create a full numeric type input (all `react-number-format` props are allowed on this component)
```jsx
<Input>
<Input.Number name="amount" placeholder="0.0" inputMode="decimal" />
</Input>
```
> feat: add Input.Number component

- design-system/react/README.md
just fixed some typos in the readme file located in fuil-ui/design-system/react readme file.
> docs: design-system-readme-typos

- .changeset/fresh-chicken-help.md
- design-system/react/src/components/Form/FormControl.tsx
- design-system/react/src/components/Icon/Icon.tsx
- design-system/react/src/components/IconButton/IconButton.tsx
- design-system/react/src/components/Input/InputElement.tsx
- design-system/react/src/components/InputPassword/InputPassword.stories.tsx
- design-system/react/src/components/InputPassword/InputPassword.test.tsx
- design-system/react/src/components/InputPassword/InputPassword.tsx
- design-system/react/src/components/InputPassword/index.tsx
- design-system/react/src/components/index.tsx
> feat(react): add InputPassword component

- .changeset/fast-nails-jog.md
- design-system/react/package.json
- design-system/react/src/components/Avatar/Avatar.stories.tsx
- design-system/react/src/components/Avatar/Avatar.tsx
- design-system/react/src/components/Avatar/AvatarGenerated.tsx
- pnpm-lock.yaml
✨ Fix #120 
This component uses [jdenticon](https://jdenticon.com/get-started/) library to generate a unique avatar SVG image based on a hash.
> feat(react): add Avatar.Generated component

- .changeset/weak-numbers-cheat.md
- design-system/react/package.json
- design-system/react/src/components/Button/Button.tsx
- design-system/react/src/components/Copyable/Copyable.tsx
- pnpm-lock.yaml
> fix(react): copyable component

- .changeset/pink-seas-wash.md
- design-system/react/src/components/Copyable/Copyable.tsx
> Fix: Copyable icon padding

- .changeset/silly-apples-deny.md
- design-system/react/src/components/Dropdown/Dropdown.test.tsx
- design-system/react/src/components/PasswordStrength/PasswordStrength.stories.tsx
- design-system/react/src/components/PasswordStrength/PasswordStrength.test.tsx
- design-system/react/src/components/PasswordStrength/PasswordStrength.tsx
- design-system/react/src/components/PasswordStrength/constants/index.ts
- design-system/react/src/components/PasswordStrength/constants/passwordDictionary.ts
- design-system/react/src/components/PasswordStrength/hooks/index.ts
- design-system/react/src/components/PasswordStrength/hooks/usePasswordStrength.ts
- design-system/react/src/components/PasswordStrength/index.tsx
- design-system/react/src/components/PasswordStrength/styles.ts
- design-system/react/src/components/PasswordStrength/types/index.ts
- design-system/react/src/components/PasswordStrength/utils/index.ts
- design-system/react/src/components/PasswordStrength/utils/passwordStrength.test.ts
- design-system/react/src/components/PasswordStrength/utils/passwordStrength.ts
- design-system/react/src/components/index.tsx
NOTE: I Already noticed that the arrow is not showing seems that when i place the position as start it hides the arrow, I'm trying to see why that is happening
> feat(design-system): password-strength

- .changeset/little-papayas-tickle.md
- design-system/react/src/components/Copyable/Copyable.stories.tsx
- design-system/react/src/components/Copyable/Copyable.tsx
> feat: Allow Copyable to accept iconProps opcionally

- .changeset/clever-terms-divide.md
- design-system/react/src/components/Copyable/Copyable.tsx
> feat: make iconProps props optional

- .changeset/fast-items-protect.md
- design-system/react/package.json
- design-system/react/src/components/ContentLoader/ContentLoader.stories.tsx
- design-system/react/src/components/ContentLoader/ContentLoader.test.tsx
- design-system/react/src/components/ContentLoader/ContentLoader.tsx
- design-system/react/src/components/ContentLoader/ContentLoaderRect.tsx
- design-system/react/src/components/ContentLoader/index.tsx
- design-system/react/src/components/InputAmount/InputAmount.stories.tsx
- design-system/react/src/components/InputAmount/InputAmount.test.tsx
- design-system/react/src/components/InputAmount/InputAmount.tsx
- design-system/react/src/components/InputAmount/InputAmountLoader.tsx
- design-system/react/src/components/InputAmount/index.tsx
- design-system/react/src/components/InputAmount/utils.test.tsx
- design-system/react/src/components/InputAmount/utils.tsx
- design-system/react/src/utils/css.ts
- pnpm-lock.yaml
closes: #179 
- Also, add a loader component with responsive support.
> feat: add input amount and loader component

- .changeset/slow-flies-protect.md
- design-system/react/src/components/index.tsx
> fix: exports for InputAmount and ContentLoader

- .changeset/famous-adults-knock.md
this PR introduces the correct changeset for the PR #197
> chore: release for Password Strength feature

- .changeset/green-coins-own.md
- design-system/react/src/components/PasswordStrength/PasswordStrength.test.tsx
- design-system/react/src/components/PasswordStrength/PasswordStrength.tsx
> fix: avoid PasswordStrength moving focus to modal.

- design-system/react/src/components/PasswordStrength/utils/passwordStrength.test.ts
- design-system/react/src/components/PasswordStrength/utils/passwordStrength.ts
> feat: password strength now accepting symbols starting.

- .changeset/config.json
- design-system/css/package.json
- design-system/tokens/package.json
- pnpm-lock.yaml
> fix: add tokens package access public

- design-system/react/src/components/ButtonGroup/ButtonGroup.stories.tsx
- design-system/react/src/components/ButtonGroup/ButtonGroup.tsx
- design-system/react/src/components/ButtonGroup/defs.ts
- design-system/react/src/components/ButtonGroup/styles.ts
- design-system/react/src/defs.ts
closes FRO-147
Update the ButtonGroup component to the new API.
> feat: update the ButtonGroup component

- design-system/react/src/components/Checkbox/Checkbox.stories.tsx
- design-system/react/src/components/Checkbox/Checkbox.tsx
- design-system/react/src/components/Checkbox/defs.ts
- design-system/react/src/components/Checkbox/styles.ts
- design-system/react/src/defs.ts
closes [FRO-155](https://linear.app/fuel-network/issue/FRO-155/update-the-checkbox-component)
> feat: upgrade the Checkbox component

- .changeset/nine-wombats-hope.md
- design-system/react/src/components/CardList/CardList.stories.tsx
- design-system/react/src/components/CardList/CardList.tsx
- design-system/react/src/components/CardList/CardListItem.tsx
- design-system/react/src/components/CardList/defs.ts
- design-system/react/src/components/CardList/styles.ts
- design-system/react/src/defs.ts
closes [FRO-154](https://linear.app/fuel-network/issue/FRO-154/update-the-cardlist-component)
> feat: upgrade CardList component

- design-system/react/src/components/CardList/CardList.tsx
- design-system/react/src/components/CardList/CardListItem.tsx
> fix: pass all props to cardItem and CardList

- design-system/react/src/components/InputAmount/InputAmount.tsx
- design-system/react/src/components/Tabs/styles.ts
> fix: remove mono font from Tab + font sizes in InputAmount

- design-system/react/src/components/Alert/styles.ts
- pnpm-lock.yaml
> feat(Alert): apply new Layout to Alert component

- .changeset/new-deers-behave.md
> chore: add changeset

- .changeset/smooth-needles-build.md
- design-system/react/src/components/Avatar/Avatar.stories.tsx
- design-system/react/src/components/Avatar/defs.ts
- design-system/react/src/components/Avatar/hooks/useAvatarGenerated.tsx
> fix: allow custom sizes for avatar generated

- .changeset/light-lies-love.md
- design-system/css/src/mixins/layers.ts
- design-system/react/.storybook/preview.tsx
- design-system/tokens/figma/themes/colors-dark.json
- design-system/tokens/figma/themes/colors-light.json
- design-system/tokens/src/definitions/semantics.mjs
> fix: adjust semantics colors

- .changeset/orange-monkeys-vanish.md
- design-system/react/src/components/InputAmount/InputAmount.stories.tsx
- design-system/react/src/components/InputAmount/InputAmount.tsx
On this PR;
- Improve the input amount UI,
- Reducing the spacing sizes
- Making labels optional
- Change MAX button style to be bring less attention to it
> feat: improve amount input UI

- .changeset/fast-dolls-count.md
- design-system/react/src/components/Nav/Nav.stories.tsx
- design-system/react/src/components/Nav/NavLogo.tsx
- design-system/react/src/components/Nav/NavMenuItem.tsx
- design-system/react/src/components/Nav/defs.ts
- design-system/react/src/components/Nav/styles.ts
Change navbar logo component structure to accept click and other properties to the container.
> feat: add on click to nav logo
